/**
 * 72 首小学必背古诗词数据
 * 按年级分组：学前 (PRESCHOOL) / 一年级 ~ 五年级 (GRADE_1 ~ GRADE_5)
 */

// 学习状态枚举
export const Status = {
  UNLEARNED: "UNLEARNED",
  PARTIAL: "PARTIAL",
  REVIEW: "REVIEW",
  MASTERED: "MASTERED",
};

// 年级标签映射
export const GradeLabels = {
  ALL: "全部",
  PRESCHOOL: "学前",
  GRADE_1: "一年级",
  GRADE_2: "二年级",
  GRADE_3: "三年级",
  GRADE_4: "四年级",
  GRADE_5: "五年级",
};

// 状态标签映射
export const StatusLabels = {
  ALL: "全部",
  UNLEARNED: "未背",
  PARTIAL: "一半",
  REVIEW: "再练",
  MASTERED: "已记",
};

// 学前古诗
const preschool = [
  {
    id: 3,
    title: "乐游原",
    author: "李商隐",
    dynasty: "唐",
    content: ["向晚意不适，", "驱车登古原。", "夕阳无限好，", "只是近黄昏。"],
    grade: "PRESCHOOL",
  },
  {
    id: 5,
    title: "悯农二首(其一)",
    author: "李绅",
    dynasty: "唐",
    content: ["春种一粒粟，", "秋收万颗子。", "四海无闲田，", "农夫犹饿死。"],
    grade: "PRESCHOOL",
  },
  {
    id: 6,
    title: "池上",
    author: "白居易",
    dynasty: "唐",
    content: ["小娃撑小艇，", "偷采白莲回。", "不解藏踪迹，", "浮萍一道开。"],
    grade: "PRESCHOOL",
  },
  {
    id: 7,
    title: "题都城南庄",
    author: "崔护",
    dynasty: "唐",
    content: [
      "去年今日此门中，",
      "人面桃花相映红。",
      "人面不知何处去，",
      "桃花依旧笑春风。",
    ],
    grade: "PRESCHOOL",
  },
  {
    id: 8,
    title: "从军行",
    author: "王昌龄",
    dynasty: "唐",
    content: [
      "青海长云暗雪山，",
      "孤城遥望玉门关。",
      "黄沙百战穿金甲，",
      "不破楼兰终不还。",
    ],
    grade: "PRESCHOOL",
  },
  {
    id: 9,
    title: "墨梅",
    author: "王冕",
    dynasty: "元",
    content: [
      "吾家洗砚池头树，",
      "朵朵花开淡墨痕。",
      "不要人夸好颜色，",
      "只留清气满乾坤。",
    ],
    grade: "PRESCHOOL",
  },
  {
    id: 10,
    title: "咏柳",
    author: "贺知章",
    dynasty: "唐",
    content: [
      "碧玉妆成一树高，",
      "万条垂下绿丝绦。",
      "不知细叶谁裁出，",
      "二月春风似剪刀。",
    ],
    grade: "PRESCHOOL",
  },
  {
    id: 11,
    title: "风",
    author: "李峤",
    dynasty: "唐",
    content: ["解落三秋叶，", "能开二月花。", "过江千尺浪，", "入竹万竿斜。"],
    grade: "PRESCHOOL",
  },
  {
    id: 12,
    title: "夜宿山寺",
    author: "李白",
    dynasty: "唐",
    content: ["危楼高百尺，", "手可摘星辰。", "不敢高声语，", "恐惊天上人。"],
    grade: "PRESCHOOL",
  },
  {
    id: 14,
    title: "寻隐者不遇",
    author: "贾岛",
    dynasty: "唐",
    content: ["松下问童子，", "言师采药去。", "只在此山中，", "云深不知处。"],
    grade: "PRESCHOOL",
  },
  {
    id: 15,
    title: "辛夷坞",
    author: "王维",
    dynasty: "唐",
    content: ["木末芙蓉花，", "山中发红萼。", "涧户寂无人，", "纷纷开且落。"],
    grade: "PRESCHOOL",
  },
  {
    id: 16,
    title: "古别离",
    author: "孟郊",
    dynasty: "唐",
    content: ["欲展清宣道，", "暂借明月光。", "不如池上水，", "犹解两相忘。"],
    grade: "PRESCHOOL",
  },
  {
    id: 17,
    title: "游子吟",
    author: "孟郊",
    dynasty: "唐",
    content: ["慈母手中线，", "游子身上衣。", "临行密密缝，", "意恐迟迟归。"],
    grade: "PRESCHOOL",
  },
  {
    id: 18,
    title: "柳溪",
    author: "韩愈",
    dynasty: "唐",
    content: ["一溪流水满，", "十里柳花香。", "不道官闲事，", "唯看水色光。"],
    grade: "PRESCHOOL",
  },
  {
    id: 19,
    title: "画鸡",
    author: "唐寅",
    dynasty: "明",
    content: [
      "头上红冠不用裁，",
      "满身雪白走将来。",
      "平生不敢轻言语，",
      "一叫千门万户开。",
    ],
    grade: "PRESCHOOL",
  },
  {
    id: 20,
    title: "古朗月行",
    author: "李白",
    dynasty: "唐",
    content: ["小时不识月，", "呼作白玉盘。", "又疑瑶台镜，", "飞在青云端。"],
    grade: "PRESCHOOL",
  },
  {
    id: 21,
    title: "劳劳亭",
    author: "李白",
    dynasty: "唐",
    content: ["天下伤心处，", "劳劳送客亭。", "春风知别苦，", "不遣柳条青。"],
    grade: "PRESCHOOL",
  },
  {
    id: 22,
    title: "五岁吟花",
    author: "陈知玄",
    dynasty: "唐",
    content: ["花开满树红，", "花落满枝空。", "唯余花里蕊，", "颜色不曾同。"],
    grade: "PRESCHOOL",
  },
  {
    id: 24,
    title: "登幽州台歌",
    author: "陈子昂",
    dynasty: "唐",
    content: [
      "前不见古人，",
      "后不见来者。",
      "念天地之悠悠，",
      "独怆然而涕下。",
    ],
    grade: "PRESCHOOL",
  },
  {
    id: 25,
    title: "中秋夜",
    author: "李峤",
    dynasty: "唐",
    content: ["圆魄上寒空，", "皆言四海同。", "安知千里外，", "不有雨兼风。"],
    grade: "PRESCHOOL",
  },
  {
    id: 26,
    title: "月下独酌",
    author: "李白",
    dynasty: "唐",
    content: ["花间一壶酒，", "独酌无相亲。", "举杯邀明月，", "对影成三人。"],
    grade: "PRESCHOOL",
  },
  {
    id: 28,
    title: "滁州西涧",
    author: "韦应物",
    dynasty: "唐",
    content: [
      "独怜幽草涧边生，",
      "上有黄鹂深树鸣。",
      "春潮带雨晚来急，",
      "野渡无人舟自横。",
    ],
    grade: "PRESCHOOL",
  },
  {
    id: 30,
    title: "花非花",
    author: "白居易",
    dynasty: "唐",
    content: [
      "花非花，雾非雾。",
      "夜半来，天明去。",
      "来如春梦几多时？",
      "离似朝云无觅处。",
    ],
    grade: "PRESCHOOL",
  },
  {
    id: 32,
    title: "弟子规",
    author: "李毓秀",
    dynasty: "清",
    content: [
      "弟子规，圣人训。",
      "首孝悌，次谨信。",
      "泛爱众，而亲仁。",
      "有余力，则学文。",
    ],
    grade: "PRESCHOOL",
  },
];

// 一年级
const grade1 = [
  {
    id: 101,
    title: "咏鹅",
    author: "骆宾王",
    dynasty: "唐",
    content: ["鹅，鹅，鹅，", "曲项向天歌。", "白毛浮绿水，", "红掌拨清波。"],
    grade: "GRADE_1",
  },
  {
    id: 102,
    title: "静夜思",
    author: "李白",
    dynasty: "唐",
    content: ["床前明月光，", "疑是地上霜。", "举头望明月，", "低头思故乡。"],
    grade: "GRADE_1",
  },
  {
    id: 103,
    title: "春晓",
    author: "孟浩然",
    dynasty: "唐",
    content: ["春眠不觉晓，", "处处闻啼鸟。", "夜来风雨声，", "花落知多少。"],
    grade: "GRADE_1",
  },
  {
    id: 104,
    title: "村居",
    author: "高鼎",
    dynasty: "清",
    content: [
      "草长莺飞二月天，",
      "拂堤杨柳醉春烟。",
      "儿童散学归来早，",
      "忙趁东风放纸鸢。",
    ],
    grade: "GRADE_1",
  },
  {
    id: 105,
    title: "所见",
    author: "袁枚",
    dynasty: "清",
    content: ["牧童骑黄牛，", "歌声振林樾。", "意欲捕鸣蝉，", "忽然闭口立。"],
    grade: "GRADE_1",
  },
  {
    id: 106,
    title: "小池",
    author: "杨万里",
    dynasty: "宋",
    content: [
      "泉眼无声惜细流，",
      "树阴照水爱晴柔。",
      "小荷才露尖尖角，",
      "早有蜻蜓立上头。",
    ],
    grade: "GRADE_1",
  },
  {
    id: 107,
    title: "画",
    author: "王维",
    dynasty: "唐",
    content: ["远看山有色，", "近听水无声。", "春去花还在，", "人来鸟不惊。"],
    grade: "GRADE_1",
  },
  {
    id: 108,
    title: "一去二三里",
    author: "邵雍",
    dynasty: "宋",
    content: ["一去二三里，", "烟村四五家。", "亭台六七座，", "八九十枝花。"],
    grade: "GRADE_1",
  },
];

// 二年级
const grade2 = [
  {
    id: 201,
    title: "山行",
    author: "杜牧",
    dynasty: "唐",
    content: [
      "远上寒山石径斜，",
      "白云生处有人家。",
      "停车坐爱枫林晚，",
      "霜叶红于二月花。",
    ],
    grade: "GRADE_2",
  },
  {
    id: 202,
    title: "赠刘景文",
    author: "苏轼",
    dynasty: "宋",
    content: [
      "荷尽已无擎雨盖，",
      "菊残犹有傲霜枝。",
      "一年好景君须记，",
      "正是橙黄橘绿时。",
    ],
    grade: "GRADE_2",
  },
  {
    id: 203,
    title: "回乡偶书",
    author: "贺知章",
    dynasty: "唐",
    content: [
      "少小离家老大回，",
      "乡音无改鬓毛衰。",
      "儿童相见不相识，",
      "笑问客从何处来。",
    ],
    grade: "GRADE_2",
  },
  {
    id: 204,
    title: "赠汪伦",
    author: "李白",
    dynasty: "唐",
    content: [
      "李白乘舟将欲行，",
      "忽闻岸上踏歌声。",
      "桃花潭水深千尺，",
      "不及汪伦送我情。",
    ],
    grade: "GRADE_2",
  },
  {
    id: 205,
    title: "草",
    author: "白居易",
    dynasty: "唐",
    content: ["离离原上草，", "一岁一枯荣。", "野火烧不尽，", "春风吹又生。"],
    grade: "GRADE_2",
  },
  {
    id: 206,
    title: "宿新市徐公店",
    author: "杨万里",
    dynasty: "宋",
    content: [
      "篱落疏疏一径深，",
      "树头新绿未成阴。",
      "儿童急走追黄蝶，",
      "飞入菜花无处寻。",
    ],
    grade: "GRADE_2",
  },
  {
    id: 207,
    title: "望庐山瀑布",
    author: "李白",
    dynasty: "唐",
    content: [
      "日照香炉生紫烟，",
      "遥看瀑布挂前川。",
      "飞流直下三千尺，",
      "疑是银河落九天。",
    ],
    grade: "GRADE_2",
  },
  {
    id: 208,
    title: "绝句",
    author: "杜甫",
    dynasty: "唐",
    content: [
      "两个黄鹂鸣翠柳，",
      "一行白鹭上青天。",
      "窗含西岭千秋雪，",
      "门泊东吴万里船。",
    ],
    grade: "GRADE_2",
  },
];

// 三年级
const grade3 = [
  {
    id: 301,
    title: "九月九日忆山东兄弟",
    author: "王维",
    dynasty: "唐",
    content: [
      "独在异乡为异客，",
      "每逢佳节倍思亲。",
      "遥知兄弟登高处，",
      "遍插茱萸少一人。",
    ],
    grade: "GRADE_3",
  },
  {
    id: 302,
    title: "夜书所见",
    author: "叶绍翁",
    dynasty: "宋",
    content: [
      "萧萧梧叶送寒声，",
      "江上秋风动客情。",
      "知有儿童挑促织，",
      "夜深篱落一灯明。",
    ],
    grade: "GRADE_3",
  },
  {
    id: 303,
    title: "饮湖上初晴后雨",
    author: "苏轼",
    dynasty: "宋",
    content: [
      "水光潋滟晴方好，",
      "山色空蒙雨亦奇。",
      "欲把西湖比西子，",
      "淡妆浓抹总相宜。",
    ],
    grade: "GRADE_3",
  },
  {
    id: 304,
    title: "望天门山",
    author: "李白",
    dynasty: "唐",
    content: [
      "天门中断楚江开，",
      "碧水东流至此回。",
      "两岸青山相对出，",
      "孤帆一片日边来。",
    ],
    grade: "GRADE_3",
  },
  {
    id: 305,
    title: "早发白帝城",
    author: "李白",
    dynasty: "唐",
    content: [
      "朝辞白帝彩云间，",
      "千里江陵一日还。",
      "两岸猿声啼不住，",
      "轻舟已过万重山。",
    ],
    grade: "GRADE_3",
  },
  {
    id: 306,
    title: "采莲曲",
    author: "王昌龄",
    dynasty: "唐",
    content: [
      "荷叶罗裙一色裁，",
      "芙蓉向脸两边开。",
      "乱入池中看不见，",
      "闻歌始觉有人来。",
    ],
    grade: "GRADE_3",
  },
  {
    id: 307,
    title: "绝句",
    author: "杜甫",
    dynasty: "唐",
    content: ["迟日江山丽，", "春风花草香。", "泥融飞燕子，", "沙暖睡鸳鸯。"],
    grade: "GRADE_3",
  },
  {
    id: 308,
    title: "惠崇春江晚景",
    author: "苏轼",
    dynasty: "宋",
    content: [
      "竹外桃花三两枝，",
      "春江水暖鸭先知。",
      "蒌蒿满地芦芽短，",
      "正是河豚欲上时。",
    ],
    grade: "GRADE_3",
  },
];

// 四年级
const grade4 = [
  {
    id: 401,
    title: "独坐敬亭山",
    author: "李白",
    dynasty: "唐",
    content: ["众鸟高飞尽，", "孤云独去闲。", "相看两不厌，", "只有敬亭山。"],
    grade: "GRADE_4",
  },
  {
    id: 402,
    title: "望洞庭",
    author: "刘禹锡",
    dynasty: "唐",
    content: [
      "湖光秋月两相和，",
      "潭面无风镜未磨。",
      "遥望洞庭山水翠，",
      "白银盘里一青螺。",
    ],
    grade: "GRADE_4",
  },
  {
    id: 403,
    title: "忆江南",
    author: "白居易",
    dynasty: "唐",
    content: [
      "江南好，",
      "风景旧曾谙。",
      "日出江花红胜火，",
      "春来江水绿如蓝。",
      "能不忆江南？",
    ],
    grade: "GRADE_4",
  },
  {
    id: 404,
    title: "乡村四月",
    author: "翁卷",
    dynasty: "宋",
    content: [
      "绿遍山原白满川，",
      "子规声里雨如烟。",
      "乡村四月闲人少，",
      "才了蚕桑又插田。",
    ],
    grade: "GRADE_4",
  },
  {
    id: 405,
    title: "四时田园杂兴",
    author: "范成大",
    dynasty: "宋",
    content: [
      "昼出耘田夜绩麻，",
      "村庄儿女各当家。",
      "童孙未解供耕织，",
      "也傍桑阴学种瓜。",
    ],
    grade: "GRADE_4",
  },
  {
    id: 406,
    title: "渔歌子",
    author: "张志和",
    dynasty: "唐",
    content: [
      "西塞山前白鹭飞，",
      "桃花流水鳜鱼肥。",
      "青箬笠，绿蓑衣，",
      "斜风细雨不须归。",
    ],
    grade: "GRADE_4",
  },
  {
    id: 407,
    title: "送元二使安西",
    author: "王维",
    dynasty: "唐",
    content: [
      "渭城朝雨浥轻尘，",
      "客舍青青柳色新。",
      "劝君更尽一杯酒，",
      "西出阳关无故人。",
    ],
    grade: "GRADE_4",
  },
  {
    id: 408,
    title: "凉州词",
    author: "王之涣",
    dynasty: "唐",
    content: [
      "黄河远上白云间，",
      "一片孤城万仞山。",
      "羌笛何须怨杨柳，",
      "春风不度玉门关。",
    ],
    grade: "GRADE_4",
  },
  {
    id: 409,
    title: "登鹳雀楼",
    author: "王之涣",
    dynasty: "唐",
    content: ["白日依山尽，", "黄河入海流。", "欲穷千里目，", "更上一层楼。"],
    grade: "GRADE_4",
  },
  {
    id: 410,
    title: "江雪",
    author: "柳宗元",
    dynasty: "唐",
    content: ["千山鸟飞绝，", "万径人踪灭。", "孤舟蓑笠翁，", "独钓寒江雪。"],
    grade: "GRADE_4",
  },
];

// 五年级
const grade5 = [
  {
    id: 501,
    title: "泊船瓜洲",
    author: "王安石",
    dynasty: "宋",
    content: [
      "京口瓜洲一水间，",
      "钟山只隔数重山。",
      "春风又绿江南岸，",
      "明月何时照我还。",
    ],
    grade: "GRADE_5",
  },
  {
    id: 502,
    title: "秋夜将晓出篱门迎凉有感",
    author: "陆游",
    dynasty: "宋",
    content: [
      "三万里河东入海，",
      "五千仞岳上摩天。",
      "遗民泪尽胡尘里，",
      "南望王师又一年。",
    ],
    grade: "GRADE_5",
  },
  {
    id: 503,
    title: "示儿",
    author: "陆游",
    dynasty: "宋",
    content: [
      "死去元知万事空，",
      "但悲不见九州同。",
      "王师北定中原日，",
      "家祭无忘告乃翁。",
    ],
    grade: "GRADE_5",
  },
  {
    id: 504,
    title: "己亥杂诗",
    author: "龚自珍",
    dynasty: "清",
    content: [
      "九州生气恃风雷，",
      "万马齐喑究可哀。",
      "我劝天公重抖擞，",
      "不拘一格降人材。",
    ],
    grade: "GRADE_5",
  },
  {
    id: 505,
    title: "枫桥夜泊",
    author: "张继",
    dynasty: "唐",
    content: [
      "月落乌啼霜满天，",
      "江枫渔火对愁眠。",
      "姑苏城外寒山寺，",
      "夜半钟声到客船。",
    ],
    grade: "GRADE_5",
  },
  {
    id: 506,
    title: "长相思",
    author: "纳兰性德",
    dynasty: "清",
    content: [
      "山一程，水一程，",
      "身向榆关那畔行，",
      "夜深千丈。",
      "风一更，雪一更，",
      "聒碎乡心梦不成，",
      "故园无此声。",
    ],
    grade: "GRADE_5",
  },
];

// 导出全部诗词
export const allPoems = [
  ...preschool,
  ...grade1,
  ...grade2,
  ...grade3,
  ...grade4,
  ...grade5,
];
